from .db import db
from .base_model import BaseModel
from .roles_model import Role
from .users_model import User
from .Privilege_model import Privilege
from .UserPrivilege_model import UserPrivilege
from .Juegos_model import Juegos
from .proyectos_model import Proyectos
from .Materias_model import Materia
from .preguntas_model import Question
from .respuesta_model import Answer
from .pass_codes import PasswordResetCode